---

- hosts: all
  become: true
  tasks:

  - name: install vim-vox
    apt:
      name: vim-nox
      state: latest
    when: ansible_ditribution == "Ubuntu"
#    when: ansible_distribution in ["Debian", "Ubuntu"]
#    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
