---

- hosts: all
  become: true
  tasks:

  - name: uninstall vim-vox
    apt:
      name: vim-nox
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]
#    when: ansible_distribution == "Ubuntu"
